spring:
  datasource:
    url: jdbc:postgresql://localhost:3001/itil-events
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      hbm2ddl:
        auto: update
      ejb:
        naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
      show_sql: true
      format_sql: true
      use_sql_comments: false
      type: all
      disableConnectionTracking: true
      default_schema: dental

